resolver: lts-13.21

packages:
  - distributed-dataset
  - distributed-dataset-aws
  - distributed-dataset-opendatasets
  - examples/gh

extra-deps:
  - stratosphere-0.36.0
  - amazonka-s3-streaming-1.0.0.1

docker:
  enable: true
  stack-exe: download
