resolver: lts-10.10

packages:
  - serverless-execute
  - serverless-execute-aws-lambda
  - serverless-batch

extra-deps:
  - stratosphere-0.19.1

allow-newer: true

nix: 
  enable: true
  packages:
    - zlib
    - unzip
