resolver: lts-10.9

packages:
  - serverless-execute
  - serverless-execute-aws-lambda

extra-deps:
  - amazonka-1.5.0
  - amazonka-cloudformation-1.5.0
  - amazonka-core-1.5.0
  - amazonka-lambda-1.5.0
  - amazonka-s3-1.5.0

allow-newer: true
