resolver: lts-13.19

packages:
  - distributed-dataset
  - distributed-dataset-aws
  - distributed-dataset-opendatasets
  - examples/gh

extra-deps:
  - stratosphere-0.36.0

docker:
  enable: true
  stack-exe: download
