resolver: lts-12.16

packages:
  - distributed-fork
  - distributed-fork-aws-lambda
  - examples

extra-deps:
  - git: https://github.com/brendanhay/amazonka.git
    commit: 248f7b2a7248222cc21cef6194cd1872ba99ac5d
    subdirs:
      - amazonka

nix:
  packages:
    - zlib
    - zlibStatic.static
    - bzip2
    - (bzip2.override { linkStatic = true; })
    - glibc
    - glibc.static
    - (gmp.override { withStatic = true; })
    - unzip
