resolver: lts-10.10

packages:
  - serverless-execute
  - serverless-execute-aws-lambda

extra-deps:
  - stratosphere-0.19.1

allow-newer: true

nix: 
  packages:
    - zlib
    - zlibStatic.static
    - glibc
    - glibc.static
    - (gmp.override { withStatic = true; })
    - unzip
