resolver: lts-15.15

packages:
  - distributed-dataset
  - distributed-dataset-aws
  - distributed-dataset-opendatasets
  - examples/gh

extra-deps:
  - amazonka-s3-streaming-1.1.0.0

allow-newer: true

docker:
  enable: true
  image: utdemir/ghc-musl:v7-libgmp-ghc883
