resolver: lts-10.10

packages:
  - serverless-execute
  - serverless-execute-aws-lambda
  - examples

extra-deps:
  - async-pool-0.9.0.2

nix:
  packages:
    - file
    - zlib
    - zlibStatic.static
    - bzip2
    - (bzip2.override { linkStatic = true; })
    - glibc
    - glibc.static
    - (gmp.override { withStatic = true; })
    - unzip
