resolver: lts-14.3

packages:
  - distributed-dataset
  - distributed-dataset-aws
  - distributed-dataset-opendatasets
  - examples/gh

extra-deps:
  - amazonka-1.6.1
  - amazonka-cloudformation-1.6.1
  - amazonka-core-1.6.1
  - amazonka-lambda-1.6.1
  - amazonka-s3-1.6.1
  - amazonka-sqs-1.6.1
  - amazonka-s3-streaming-1.0.0.2

allow-newer: true

docker:
  enable: true
  image: utdemir/ghc-musl:v1-ghc865
  set-user: false
