nix-base: &nix-base
  docker:
    - image: nixos/nix:1.11
  steps:
    - checkout
    - run: nix-build --argstr compiler "$COMPILER"

version: 2
jobs:
  nix-ghc802:
    <<: *nix-base
    environment:
      COMPILER: ghc802
  nix-ghc822:
    <<: *nix-base
    environment:
      COMPILER: ghc822
  stack:
    docker:
      - image: fpco/stack-build:lts-10.10
    steps:
      - checkout
      - run: stack build
workflows:
  version: 2
  build_and_test:
    jobs:
      - nix-ghc802
      - nix-ghc822
      - stack
