name: examples

ghc-options: -Wall -static -optl-static -optl-pthread -fPIC

executables:
  lambda:
    main: lambda.hs
    dependencies:
      - base
      - serverless-execute
      - serverless-execute-aws-lambda
      - async
      - text
      - http-conduit
  gh:
    main: gh.hs
    dependencies:
      - base
      - serverless-execute
      - serverless-execute-aws-lambda
      - aeson
      - conduit
      - conduit-combinators
      - conduit-extra
      - containers
      - http-conduit
      - lens
      - lens-aeson
      - monoidal-containers
      - ndjson-conduit
      - text
      - time
      - vector
