name: "nix build"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v2
    - uses: cachix/cachix-action@v2
      with:
        cachixPush: utdemir
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
